name: Run Instagram Scraper Hourly

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 9
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GOOGLE_KEY2: ${{ secrets.GOOGLE_KEY2 }}
          GOOGLE_KEY3: ${{ secrets.GOOGLE_KEY3 }}
          GOOGLE_KEY4: ${{ secrets.GOOGLE_KEY4 }}
          GOOGLE_KEY5: ${{ secrets.GOOGLE_KEY5 }}

        run: |
          echo "$GOOGLE_KEY" > key.json
          echo "$GOOGLE_KEY2" > key2.json
          echo "$GOOGLE_KEY3" > key3.json
          echo "$GOOGLE_KEY4" > key4.json
          echo "$GOOGLE_KEY5" > key5.json
          python gossip.py
          python gadinsider.py
          python celebbox.py
          python celebpost.py
          python geosuper.py

  
